### ISSUE TITLE
Add Info form - 2 fields do not prevent unlimited amount of data from being entered

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#10]
This is not a bug, per se; it's more of a nice to have. 

On the Add Info form, there are two fields that will allow a user to enter unlimited amount of data. The form cannot be submitted because for each field there is a message indicating data length too long, but it would e good if these two fields prevented data from being enter by setting a limit on the amount of data that can be entered. The fields are: 'Address' and 'Website URL'.

**Comment by chrisgeyer** [comment]
max length attributes can be added to those fields but we would need a recommended length.

**Comment by chavisa** [comment]
If you are asking me, I would recommend each be set at 100 characters, which appears to be the default length assigned to other fields in the form.

**Comment by chrisgeyer** [comment]
attributes were added for maxlength of 100

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
