### ISSUE TITLE
Add Info form can be submitted with invalid Website URL format

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#11]
There are two issues:

1. The Add Info form indicates "Your full URL e.g. "http://www.yoursite.com" is required, but the form can be successfully submitted if the "http://" is missing. I just entered 'espn.com' and the form submitted successfully.

2. The  Add Info form can be submitted with any text in the 'Website URL' field.  for example, I was able to submit with '123456', 'abcdef', 'http://raleighnc.'

The expectation is this field will only allow data that fits a valid URL format.

**Comment by chrisgeyer** [comment]
validation for a url was added

**Comment by Jalberque** [comment]
pushed to "http://gisdevarc1/startupdev/"

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
