### ISSUE TITLE
The 'Add Company' form title needs to be more descriptive

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#12]
Currently when the 'Add Company' button is selected the form that is displayed has the title, 'Add Something'. This should be changed to reflect the purpose of the form. 

![new picture 1](https://cloud.githubusercontent.com/assets/10038645/5724541/6484b336-9b1a-11e4-9fce-340b882b822c.png)

**Comment by chrisgeyer** [comment]
title of form changed to 'Add a Company'

**Comment by chavisa** [comment]
I am going to, "http://gisdevarc1/startupdev/" and there is no change. Still seeing the same problem as originally reported.

**Comment by Jalberque** [comment]
Update pushed to "http://gisdevarc1/startupdev/"

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
