### ISSUE TITLE
The link on the "About this Map" page displays an error message when clicked

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#14]
On the "About this Map" page, the URL "http://www.raleigh4u.com/contact/" displays an error message when selected.
1. On the main screen select the "About this Map" button
2. The "About this Map" page is displayed; at the bottom click the link  "http://www.raleigh4u.com/contact/"
3. The attached error is displayed.
![new picture](https://cloud.githubusercontent.com/assets/10038645/5725201/d9c2bb30-9b1e-11e4-962f-e47401430a6f.png)

**Comment by chrisgeyer** [comment]
link text and url were changed here as well

**Comment by chavisa** [comment]
I am going to, "http://gisdevarc1/startupdev/" and there is no change. Still seeing the same problem as originally reported.

**Comment by chrisgeyer** [comment]
changes are not live. I am making them for jim and he will push them out at a later time.

**Comment by Jalberque** [comment]
changes pushed to: "http://gisdevarc1/startupdev/"

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
