### ISSUE TITLE
The Add Job, "You're Hiring' form; When should we stop listing the job? 

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#15]
![new picture](https://cloud.githubusercontent.com/assets/10038645/5727037/0ce9e52e-9b2e-11e4-93b3-7733bc077af6.png)
The Add Job, "You're Hiring" form, there is a questions, "When should we stop listing the job?", but there is no place for that questions to be answered. The expectation is that there would be a date field after which the job should no longer be listed.

**Comment by chrisgeyer** [comment]
this looks to be additional help text for the hire date field and the date entered would be when the job is no longer displayed.

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
