### ISSUE TITLE
Add Company form does not reset when closed w/ out submitting

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#19]
I click on the Add Company button, an Add Company form is displayed. I begin to fill out the form but choose to either select 'X' to 'Close' to exit the form without submitting it. The form which I started no longer is displayed. I then select the Add Company button again to get a new form. But the new form contains the data from the previous form which was closed.

The expectation is that the new form would be blank and not contain the information the previous entry.

**Comment by chrisgeyer** [comment]
if you are in the same session this makes sense to me as an autosave like feature for the user so they don't lose data. it is not more difficult to tab through the form to enter data if something is filled in or not.
