### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#21]
1. Raleigh Start-up Admin; When a company is reviewed and rejected. What is suppose to happen other than the counter increasing by 1. Currently, if a company is rejected there is no notification of any kind.  Is an email suppose to be sent?

2. Raleigh Start-up Admin; the 'Hiring and Hiring Pending counters do not appear to be associated with any data that would cause them to increment. Am I missing something?
![new picture](https://cloud.githubusercontent.com/assets/10038645/5746557/5de04f6a-9bfe-11e4-883e-7b1f37007a92.png)

**Comment by Jalberque** [comment]
no, the the pending counter should decrease by 1.

**Comment by chavisa** [comment]
Nothing further needed. Closed.
