### ISSUE TITLE
Raleigh Startup Admin - Edit form name change

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#22]
In the Raleigh Startup Admin, when a company is selected to be edited, the form that is displayed has the title, "Edit Place". Shpuld that be changed to something more appropriate.
![new picture](https://cloud.githubusercontent.com/assets/10038645/5747022/8df2d444-9c02-11e4-84ac-ba88d2674705.png)

**Comment by chrisgeyer** [comment]
title changed to 'Edit Company'

**Comment by Jalberque** [comment]
pushed to http://gisdevarc1/startupdev/

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
