### ISSUE TITLE
Raleigh Startup Admin - When a Company is edited, required fields can be left empty

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#23]
When using the Edit function in Raleigh Start-up Admin, a company data can be with the following fields below empty. If any of the other fields are empty and save attempted the message, "All fields are required - please try again.", is displayed.

Website
Description
 Executive Name
 Executive Email
Other Contact
Number of Employees
Revenue
Funding Level
Recent Milestones 
Notes

**Comment by Jalberque** [comment]
Updated message and code to reflect some required fields: Ttile, type, address, uri, description fields are required - please try again. 

The thought is that since this is an admin screen, the administrator would have the ability to update the truly "required" data.

**Comment by chavisa** [comment]
Jim you are going to hate me for this bu there are still a couple of small changes needed. When required fields are left empty, the error message displayed is: "Ttile, type, address, uri, description fields are required - please try again." 
The problem is, there is no field description labeled Title or uri, 'Title' should be 'Company Name' and 'uri' should be 'website'. 

So, the error message that should be displayed when required fields are empty should be: 'company name, type, address, website, description fields are required - please try again.'

**Comment by Jalberque** [comment]
My error. I have updated the message to reflect screen names.

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
