### ISSUE TITLE
Raleigh Start-up Admin - (Form) Capitalize field descriptions 

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#24]
1. In Raleigh Start-up Admin, select the edit button for any company
2. The form that is displayed consists of field descriptions and the field content
3. All of the field descriptions are capitalized except for the following: revenue, notes
4. Capitalize these two field descriptions
![new picture](https://cloud.githubusercontent.com/assets/10038645/5758431/9eab30f6-9c93-11e4-8e79-e73cfebd1a1d.png)

**Comment by chrisgeyer** [comment]
revenue and notes were capitalized

**Comment by Jalberque** [comment]
pushed to http://gisdevarc1/startupdev/

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
