### ISSUE TITLE
Raleigh Start-Up Admin - Search feature only display the first 15 results

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#27]
Using the Raleigh Start-Up Admin 'Search' -  The search feature displays 15 results on a page. So if a search is performed that produces 27 results, it should display those results in two pages (15 on the first page and 12 on the second page). The problem is that when the first page displays, there is currently no way to get the second page of results to display. There is a  'Next' button, but it acts the same as the 'See All' button; when it is clicked all the listings

1. At the Raleigh Start-Up Admin 'Search', enter the value 'pa' and press enter
2. It will indicate 27 results were found and it will display 1-15/27
3. Assuming you want to see the 20th item, there is no way to see it. 
4. There are two options available, 'Next' and 'See All'. Selecting either one will negate the search result of 27 and will default to the entire listing.

**Comment by Jalberque** [comment]
admin function

**Comment by Jalberque** [comment]
Added list type to next and previous functions.
