### ISSUE TITLE
Raleigh Startup Main Map screen - Clicking API button displays HTML source data

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#28]
![new picture](https://cloud.githubusercontent.com/assets/10038645/5776995/7c9241d4-9d5c-11e4-85b1-9654a5171f65.png)

On the main map screen (top right hand corner) there is a button labeled 'API' (see above). When that button is clicked it produces a screen of HTML source code. (see below).

![new picture](https://cloud.githubusercontent.com/assets/10038645/5777057/18aec9ca-9d5d-11e4-9d6f-699419309fb3.png)

**Comment by Jalberque** [comment]
This is the startup data as an API (aplication programming Interface) http://en.wikipedia.org/wiki/Application_programming_interface. This data will let you use the start up data outside of the application. This is as designed.

**Comment by chavisa** [comment]
This was reported in error. Closed.
