### ISSUE TITLE
Raleigh Start-up main map screen - Incorrect pop-up is being displayed

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#29]
On Raleigh Start-up main map screen, on the right side are the list of companies by category. What is suppose to occur is that when a company is clicked from that list, a pop-up appears for that company appears on the map. The problem is, that the pop-up that is being displayed does not correspond to the company name picked from the list. The pop-up corresponds to the next company name on the list.
Below I have attached a screen shot of the Raleigh Start-up main map screen. I clicked on the company 'AirGlow' and the expectation I had is the pop-up for AirGlow would be displayed. But instead the pop-up for Ajinomoto North America is being displayed.  And this occurs no matter which company I select from the list.

![new picture](https://cloud.githubusercontent.com/assets/10038645/5779136/4af798ba-9d6e-11e4-8a1f-17c4365fef00.png)

**Comment by Jalberque** [comment]
Applied same query to table of contents as was applied to the map.

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
