### ISSUE TITLE
Raleigh Startup Admin - If Edit function is used to change Company Address, Map Still Shows Company at old Address

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#31]
when a new Company is added, and the address is entered, that address is marked on the calendar. If that address should change (the company moves), the expectation is that by using the Raleigh Startup Admin, edit function the new address would be entered to replace the old address and the new location would be displayed on the map. Currently, when the new addess is added, the map still points to the old address.

Attached is Eagle Video Production who were on 2201 Woodnell Drive. I used the Raleigh Startup Admin, edit function to changed the address to 219 Fayetteville St. But as you see the location for the company is still showing as Woodnell Drive.

![new picture](https://cloud.githubusercontent.com/assets/10038645/5784878/96205874-9d9e-11e4-83f6-b50d94d27648.png)

**Comment by Jalberque** [comment]
Added functionality "on save" to set lat and long to 0 and re-geocode.

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
