### ISSUE TITLE
Raleigh Start-up - Add Info and Add Company Does the Same

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#32]
In the Raleigh Start-up, the Add Info button and the Add Company button both displays the form to add a new company. Shouldn't they be named the same?

**Comment by chrisgeyer** [comment]
changed the button text on the toolbar as well as the welcome screen to both be 'Add company' which matches the form

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
