### ISSUE TITLE
Raleigh Start-up - City of Raleigh icon does not link to COR website

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#33]
![new picture 1](https://cloud.githubusercontent.com/assets/10038645/5826079/087aed9a-a0be-11e4-99fc-5a1b5d5e345c.png)
When the City of Raleigh icon (above) is clicked it does not display raleighnc.gov website; instead the Start-up Welcome screen (below) appears. The expectation is that when the  City of Raleigh icon is clicked,raleighnc.gov website will appear in a new window. 

![new picture 2](https://cloud.githubusercontent.com/assets/10038645/5826145/850762ee-a0be-11e4-843e-70b07898b79d.png)

**Comment by Jalberque** [comment]
City seal now links to Raleighnc.gov

**Comment by chrisgeyer** [comment]
standard convention is for this to link back to the 'home' page, since this is a one page app it should just refresh basically. I don't view this as connected with raleighnc.gov so I would revert this back to the old behavior.

**Comment by chavisa** [comment]
Excellent! Closed.
