### ISSUE TITLE
Raleigh Start-up - About this Map T\text font size inconsistent

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#35]
Using browser; Firefox 35.0, - The font size of the text on the About this Map information sheet is not consistent. See below. The expectation is that the font for the bullet-ed text would be the same is the non- bullet-ed text.
![new picture 1](https://cloud.githubusercontent.com/assets/10038645/5857013/3e73ff00-a216-11e4-80d5-4975fd74836b.png)

**Comment by chrisgeyer** [comment]
under modals in map.css replace

.modal .modal-body p {
font-weight: normal;
}

with this

.modal .modal-body p {
font-weight: normal;
font-size: 100%;
}

**Comment by Jalberque** [comment]
made css change in http://gisdevarc1/startupdev/

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
