### ISSUE TITLE
Raleigh Start-up - The See Map/Who's Hiring button not displaying a default value on startup

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#36]
Browser: Chrome and Firefox
When the Raleigh Startup app is initially displayed, the See Map/Who's Hiring button appears as a blue dot, instead of displaying either See Map or Who's Hiring as the default. The blue dot has to be clicked to display either See Map or Who's Hiring. 

Currently display this:  ![new picture](https://cloud.githubusercontent.com/assets/10038645/5858154/0c770fe8-a21f-11e4-824a-feea9452572d.png)

Should display: ![new picture 1](https://cloud.githubusercontent.com/assets/10038645/5858179/392fbfd0-a21f-11e4-8cb9-d8f9adb7fbb2.png)

**Comment by chrisgeyer** [comment]
Was only able to recreate this when choosing add company from the splash screen and then closing the form. Selecting view map or who's hiring worked in both browsers.

**Comment by Jalberque** [comment]
I have update to create the Who's hiring button on the add company event.

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
