### ISSUE TITLE
Raleigh Start-up - The 2 'Who's Hiring' links do not display the same

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#39]
Browser: Firefox & Chrome
Raleigh Start-up, the 'Who's Hiring' link is displayed in two places ; on the Welcome banner and on the main map page (see attachment below). When the 'Who's Hiring' link is selected on the main map page the results are: the respective technology counter displays the total number of  companies that have submitted jobs which have been approved, the map displays an icon for each of those companies.
 
But when the 'Who's Hiring' link is selected on the Welcome banner the result are the 'See map' is displayed.

The expectation is that each of the 'Who's Hiring' links will displayed the same; the respective technology counter displays the total number of  companies that have submitted jobs which have been approved and the map displays an icon for each of those companies.

![new picture](https://cloud.githubusercontent.com/assets/10038645/5960445/6273ce16-a7a3-11e4-861c-06ef80c4a71d.png)

**Comment by Jalberque** [comment]
updated code to have both the splash screen and the button on the main UI function the same.

**Comment by chavisa** [comment]
Testing successful. Closed.
