### ISSUE TITLE
Raleigh Start-up - Add Job  and Add Company forms - data not displayed clearly w/ Firefox

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#42]
Below is are Add Job forms completed using Chrome (top) and Firefox (bottom). Note that the data in each of the field with Chrome is clear and distinguishable. With Firefox it appears like the tops and bottom of data in each field is obscured. The Firefox form looks like the height of each of the fields needs to be increased.  
![new picture 1](https://cloud.githubusercontent.com/assets/10038645/6133276/d48f97e6-b126-11e4-93aa-bc6becb7df8c.png)
![new picture](https://cloud.githubusercontent.com/assets/10038645/6133278/d6a4cd9e-b126-11e4-9322-ae7109f93448.png)

**Comment by Jalberque** [comment]
I will connect with Chris G. on this tomorrow.

**Comment by Jalberque** [comment]
Updated reference to GA, which seems to have resolved the issue.
