### ISSUE TITLE
Raleigh Start-up - Add Job  and Add Company forms - No error msg display 

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#43]
For both Firefox and Chrome, for both 'Add a Job' and 'Add a Company', when the 'Submit for Review' button is selected with required fields empty, no error message is displayed.

Step Taken:
1. Using either Firefox or Chrome, open an Add a Job or Add a Company form
2. Only information into the first two fields and leave the remaining fields blank
3. Select the 'Submit for Review' button.
4. Currently either the data enter disappears and no error message is displayed or the data remains and no error message is displayed.

The expectations are:
1. If required fields are left empty and the form is submitted, an error message would either identify the specific fields that are required or say all fields are required.
2. The data which was entered correctly would remain in the fields; it would not be removed.
3. Ideally, this would be the same with Firefox and Chrome

**Comment by Jalberque** [comment]
unable to reproduce. I will connect with Allen tomorrow.

**Comment by chavisa** [comment]
I agree; unable to reproduce. Closed.
