### ISSUE TITLE
 The link "http://www.raleigh4u.com/contact/" displays an error message when clicked

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#6]
![new picture 2](https://cloud.githubusercontent.com/assets/10038645/5715733/7d968d90-9aac-11e4-8eed-08403f06fc5a.png)

On the Welcome dialogue box, the http://www.raleigh4u.com/contact/ link displays an error message when selected.

**Comment by chrisgeyer** [comment]
updated link text and changed url to http://www.raleigh4u.com/contacts/

**Comment by chavisa** [comment]
I am going to, "http://gisdevarc1/startupdev/" and there is no change. Still seeing the same problem   as originally reported.

**Comment by Jalberque** [comment]
Should be resolved  in http://gisdevarc1/startupdev
