### ISSUE TITLE
The "Add Info" form allows Title Needs to be Changed 

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#7]
The Add Info form title is currently 'Add Something'; should be changed to reflect the purpose of the form.

![new picture 5](https://cloud.githubusercontent.com/assets/10038645/5723007/ce4e18b8-9b0e-11e4-9aec-27bbc3d78d5e.png)

**Comment by chrisgeyer** [comment]
title changed to 'Add a Company'

**Comment by Jalberque** [comment]
pushed to "http://gisdevarc1/startupdev/"

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
