### ISSUE TITLE
'Add Info' form can be submitted with Required fields empty 

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#8]
The Add Info form indicates all fields are required. But the form can be successfully submitted with "Your Email"  or "Number of Employees", fields left empty:

**Comment by Jalberque** [comment]
Made all fields in "add company" required to submit form

**Comment by chavisa** [comment]
Testing successfully completed. Closed.

**Comment by chavisa** [comment]
Opened in error. Closed.
