### ISSUE TITLE
Add Info form - # of employees field allows unlimited and invalid data to be submitted

### ISSUE THREAD

**Issue by chavisa** [CORaleigh/represent-map#9]
On the "Add Info" form I am able to enter an unlimited amount of text in the 'Number of Employees' field  (see TEST DATA below) and submit the form successfully. Also, I can submit alpha characters; this field should only allow numeric characters.

TEST DATA
All Jabber changes and upgrades, must be approved by the Change Advisory Board (CAB) before production implementation. A Request for Change (RFC) is completed and submitted to the CAB, for approval, by the impacted IT Manager or their representative. RFCs are never completed or submitted by the business units, users or customers. 

1.1	Non-Emergency RFC Workflow
1.	When the RFC is started in FootPrints the default status is Open.
2.	When the sunbmitter has completed documenting the RFC and is ready for it to be reviewed, the submitted changes the Status from Open to Ready for CAB Review. If the Status is not changed the CAB has no way of knowing the submitter wants the RFC to be reviewed.
3.	 Based on the urgency and impact, the RFC is reviewed either by just the CAB Manager or the entire CAB.
a.	If the RFC is approved the status is changed to Approved and can be implements as planned.
b.	If the RFC is not approved, the status is changed to from ‘Ready for CAB Review’ back to Open and the CAB Manager update the Description section of the RFC with the reason the RFC was not approved. In addition, the CAB Manager will provide the submitter specific, detailed information of what is required for the RFC to be approved. The submitter makes the necessary modifications and again changes the status back to Ready for CAB Review to be again reviewed for approval. The process can be repeated until the RFC is approved. Then the status is changed to Approved by CAB and the RFC can be implements as planned.
4.	The change detailed in the RFC is implemented into production.
5.	The individual who created the RFC updates the RFC to indicated the results of the production emplementation and change the Status from Approved by CAB to Closed.
a.	If an RFC is approved for a change, and that change does not fix the issue, then the status of the RFC should be changed from Approved By CAB back to Open. 
b.	The issue will be worked and when another fix is ready, that same RFC can be used, but the new fix must be submitted to the CAB again for approval, as if it were a new RFC.  
1.2	Creating an RFC
When creating an RFC, the information on four tabs are required to be completed. Any field with the name displayed in red is required.
1.	General Information tab – Requests information such as title, name of submitter, priority, *status and email address of the submitter.

2.	Contact Information tab – Requests information such as name, phone number, email address, location and department of the submitter.

3.	RFC Information tab – Requests details such as services and systems affected, reason(s) for change, pre and post-production test plan, communication plan, roll back plan, if an outage is required and the amount of time required to complete the RFC. Sufficient information should be entered to allow the CAB committee to fully understand the work to be accomplished. 
*NOTE: Supporting documents may also be attached to the RFC, as appropriate.
 
1.2.1	Updating and RFC
Description tab – The section should contain a narrative of all work which has been performed to resolve the issue. It may also contain remarks which one feels is of importance to others who are working the issue.
1.2.2	Definition of Priority, Category and Urgency 
1.	In the New RFC for Change Management -- General Information section, the Priority field has three options from which to select:
a.	High – Priority set to ‘High’ indicates the RFC is an Emergency. An RFC should be considered an emergency if:
•	there is an impact to revenue
•	there is public facing issue that might cause negative impact to the City or to the IT department
•	there is a non-functioning operational system 
•	it is to correct an issue that, if not addressed, will make a system unusable 
b.	Medium – An issue for which a work-around is in place and the fix can be implemented at the next scheduled release or scheduled maintenance.
c.	Low – An issue that can wait to be addressed whenever it is convenient to do so.??????

**Comment by chrisgeyer** [comment]
validation for allowing only numbers was added

**Comment by Jalberque** [comment]
pushed to "http://gisdevarc1/startupdev/"

**Comment by chavisa** [comment]
Testing successfully completed. Closed.
